nginx:
    build: ./docker/nginx/
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app
    dns:
        - 192.168.1.13
        - 192.168.1.219
        - 8.8.8.8
        - 8.8.4.4

php:
    build: ./docker/php/
    expose:
        - 9000
    volumes_from:
        - app
    dns:
        - 192.168.1.13
        - 192.168.1.219
        - 8.8.8.8
        - 8.8.4.4

app:
    image: php:5.6-fpm
    volumes:
        - .:/var/www/applications/dashboard/current
